routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * to make new conttoller command
php artisan make:controller Frontend/IndexController --resource
*/

use Illuminate\Support\Facades\Route;

Auth::routes();


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
    ->middleware('role:admin')
    ->group(function (){

        //write your routes for backend
        Route::get('/', 'DashboardController@index')->name('dashboard');
//        products route
        Route::get('/products', 'ProductController@index')->name('product.list');
        Route::get('/product-add', 'ProductController@create')->name('product.add');
        Route::get('/product-edit/{id}', 'ProductController@edit')->name('product.edit');
//        for slug generation
        Route::get('/check_slug', 'ProductController@check_slug')->name('product.slug');
//        product create
        Route::post('/product-create', 'ProductController@store')->name('product.create');
        Route::post('/product-update', 'ProductController@update')->name('product.update');
        Route::post('/product-destroy', 'ProductController@destroy')->name('product.destroy');


//        category route
        Route::get('/category', 'CategoryController@index')->name('category.list');
        Route::get('/category-add', 'CategoryController@create')->name('category.add');
        Route::post('/category-create', 'CategoryController@store')->name('category.create');
        Route::get('/category-edit/{id}', 'CategoryController@edit')->name('category.edit');
        Route::post('/category-update', 'CategoryController@update')->name('category.update');
        Route::get('/category_slug', 'CategoryController@check_slug')->name('category.slug');

//        Order's route
        Route::get('/order','OrderController@index')->name('order.list');
        Route::get('/order/{id}','OrderController@show')->name('order.show');
        Route::get('/order-edit/{id}','OrderController@edit')->name('order.edit');
        Route::post('/order-update','OrderController@update')->name('order.update');
        Route::get('/pdf/{id}','OrderController@pdf')->name('order.pdf');


//        Slider route
        Route::get('/slider', 'SliderController@index')->name('slider.list');
        Route::get('/slider-add', 'SliderController@create')->name('slider.add');
        Route::post('/slider-create', 'SliderController@store')->name('slider.create');
        Route::get('/slider-edit/{id}', 'SliderController@edit')->name('slider.edit');
        Route::post('/slider-update', 'SliderController@update')->name('slider.update');
        Route::post('/slider-destroy', 'SliderController@destroy')->name('slider.destroy');

//        coupon route
        Route::get('coupon','CouponController@index')->name('coupon.list');
        Route::get('coupon/new','CouponController@new')->name('coupon.add');
        Route::post('coupon/create','CouponController@create')->name('coupon.create');
        Route::get('coupon/edit/{id}','CouponController@edit')->name('coupon.edit');
        Route::post('coupon/update','CouponController@update')->name('coupon.update');
        Route::post('coupon/destroy','CouponController@destroy')->name('coupon.destroy');

//        reviews controller for admin
        Route::get('reviews', 'AdminReviewController@index')->name('reviews.list');
        Route::get('reviews/show/{id}', 'AdminReviewController@show')->name('reviews.show');
        Route::post('/review-destroy', 'AdminReviewController@destroy')->name('reviews.destroy');


        //        Fetured Categories route
        Route::get('/featuredcategories', 'FeaturedCategoryController@index')->name('featuredcategories.list');
        Route::get('/featuredcategories-add', 'FeaturedCategoryController@create')->name('featuredcategories.add');
        Route::post('/featuredcategories-create', 'FeaturedCategoryController@store')->name('featuredcategories.create');
        Route::get('/featuredcategories-edit/{id}', 'FeaturedCategoryController@edit')->name('featuredcategories.edit');
        Route::post('/featuredcategories-update', 'FeaturedCategoryController@update')->name('featuredcategories.update');
        Route::post('/featuredcategories-destroy', 'FeaturedCategoryController@destroy')->name('featuredcategories.destroy');

//        sales report
        Route::get('/sales-report', 'ReportController@index')->name('report.index');

        Route::get('/users', 'FeedbackController@userList')->name('user.list');
        Route::get('/users/{id}', 'FeedbackController@userShow')->name('user.show');

        Route::get('/feedback', 'FeedbackController@index')->name('feedback.list');
        Route::get('/feedback/{id}', 'FeedbackController@show')->name('feedback.show');
        Route::get('/newsletter', 'NewsletterController@index')->name('newsletter.index');
    });


Route::name('frontend.')
    ->namespace('Frontend')
    ->group(function (){

        //write your routes for frontend
       Route::get('/','IndexController@index' )->name('index');

      // shop route
        Route::get('/shop/{product}', 'ShopController@show')->name('shop.show');
        Route::get('/shop', 'ShopController@index')->name('shop.index');

        // cart route

        Route::get('/cart', 'CartController@index')->name('cart.index');
        Route::post('/cart', 'CartController@store')->name('cart.store');
        Route::get('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
        Route::post('/cart/{product}', 'CartController@update')->name('cart.update');


        ///wish list

        Route::post('/wishlist', 'WishlistController@store')->name('wishlist.store');
        Route::get('/wishlist', 'WishlistController@index')->name('wishlist.index');
        Route::get('/wishlist/{product}', 'WishlistController@destroy')->name('wishlist.destroy');

        //checkout
        Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');

        // coupon route
        Route::post('/coupon', 'CartController@storeCoupon')->name('coupon.store');
        Route::delete('/coupon', 'CartController@destroyCoupon')->name('coupon.destroy');

        //        review
        Route::post('/review-add','ReviewController@store')->name('review.store');
//        newsletter
        Route::get('/newsletter-add', 'IndexController@newsletter')->name('newsletter.add');
        Route::post('/feedback-add', 'IndexController@feedback')->name('feedback.add');




        //my accout

        Route::get('/my-account', 'OrderIndexController@index')->middleware('auth')->name('my-account');
        Route::post('/my-account', 'OrderIndexController@store')->middleware('auth')->name('my-account.store');

        // password update
        Route::get('/password-update', 'PasswordController@index')->name('password-update');

        Route::post('update/password', 'PasswordController@update')->name('update-pass');

        Route::get('/search', 'ShopController@search')->name('search');

       Route::get('/about', function () {
                 return view('frontend.pages.about');
             });

                Route::get('/contact', function () {
                return view('frontend.pages.contact');
            });
                Route::get('/compare', function () {
                 return view('frontend.pages.compare');
             });
             Route::get('/blog', function () {
                 return view('frontend.pages.blog');
             });
             Route::get('/post', function () {
                 return view('frontend.pages.post');
             });

             Route::get('/faq', function () {
                 return view('frontend.pages.faq');
             });



    });

app/Http/Controllers/Frontend/CartController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Coupon;
use App\Product;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.pages.cart');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = Product::find($request->id);
        $rows = Cart::instance('default')->content();
        if(count($rows) > 0){


            $rowId = $rows->first()->rowId;
            if (Cart::instance('default')->content()[ $rowId ]->qty >= $product->stock){
                return back()->with('error_massage','Sorry ! You cannot add more than available quantity');
            }

            else {

                Cart::instance('default')->add($request->id, $request->name, $request->quantity, $request->price)->associate('App\Product');
                return back()->with('success_message', 'Item was added to your cart!');
            }
        }else {


            if ($request->quantity > $product->stock) {
                return back()->with('error_massage', 'Sorry ! You cannot add more than available quantity');
            } else {

                Cart::instance('default')->add($request->id, $request->name, $request->quantity, $request->price)->associate('App\Product');
                return back()->with('success_message', 'Item was added to your cart!');
            }
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        Cart::instance('default')->update($id,$request->quantity);
        return redirect()->route('frontend.cart.index')->with('alert_massage','Item is updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($rowId)
    {
        Cart::instance('default')->remove($rowId);
        return back()->with('error_massage','Item has been removed!');
        // return redirect()->route('cart.index')->with('success_message','Item was added to your cart!');

    }
    public function storeCoupon(Request $request)
    {
        $code = Coupon::where('code', $request->coupon_code)->first();

        if(!$code){
            return redirect()->route('frontend.cart.index')->with('success_message', 'Invalid coupon !');
        }
        session()->put('coupon', [
            'name' => $code->code,
            'amount' =>$code->discount( Cart::subtotal(2,'.',''))
        ]);
        return redirect()->route('frontend.cart.index')->with('success_message', 'coupon Applied ');
    }

    public function destroyCoupon()
    {
        session()->forget('coupon');
        return back()->with('success_message', 'coupon has been removed.');
    }


}

app/Http/Controllers/Frontend/CheckoutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Order;
use App\OrderIndex;
use App\OrderProduct;
use App\Product;
use Barryvdh\DomPDF\PDF;
use Cartalyst\Stripe\Laravel\Facades\Stripe;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class CheckoutController extends Controller
{

    public function index(){
        return view('frontend.pages.checkout');
    }
    public function store (Request $request){

        // dd($request->all());

        try {
            $charge = Stripe::charges()->create([
                'amount' => Cart::instance('default')->subtotal(null,null,''),
                'currency' => 'USD',
                'source' => $request->stripeToken,
                'description' => 'Order',
                'receipt_email' => $request->email,
                'metadata' => [
                    //  'contents' => $contents,
                    // 'quantity' => Cart::instance('default')->count(),
                    //  'discount' => collect(session()->get('coupon'))->toJson(),
                ],
            ]);



            //insert in to order table
            $order = Order::create(
                [
                    'user_id' => auth()->user() ? auth()->user()->id : null,
                    'billing_email' => $request->email,
                    'billing_first_name'=> $request->fname,
                    'billing_last_name'=> $request->lname,
                    'billing_phone_no'=> $request->number,
                    'billing_address'=> $request->address,
                    'billing_town'=> $request->state,
                    'billing_city'=> $request->city,
                    'billing_zip_code'=> $request->postcode,
                    'billing_discount'=> $request->cupon_amount,
                    'status' => 'Pending',
                    'billing_id' => $charge['id'],
                    'billing_discount_code'=> $request->cupon_name,
                    'billing_subtotal'=> Cart::instance('default')->subtotal(null,null,''),
                    'billing_shipping_fee'=> 0,
                    'billing_total'=> $request->total,

                ]
            );
            // Insert into order_product table
            foreach (Cart::instance('default')->content() as $item) {
                OrderProduct::create([
                    'order_id' => $order->id,
                    'product_id' => $item->model->id,
                    'quantity' => $item->qty,
                    'price' => $item->price,

                ]);
                $product = Product::find($item->model->id);
                $product->stock = $product->stock - $item->qty;
                $product->save();
            }

            $oid = $order->id;
            $ocode = substr(md5('muaj'.$oid.'saif'), 0, 15);
            $otracker = substr(md5('muaj'.$oid.'saif'), 16, 31);
            $user = auth()->user() ? auth()->user()->id : 'guest';

            $ordered_now = OrderIndex::create([
                'user_id' => $user,
                'order_no' => $oid,
                'order_code' => $ocode,
                'tracker' => $otracker
            ]);


            $uid = auth()->user() ? auth()->user()->id : 0;
            $ocode = 'FVT'. substr(md5('muaj'.$order->id.'saif'), 0, 12) ;
            $var = DB::table("Insert into `order_index`(`user`,`order_no`,`order_code`) values('$uid','$order->id','$ocode')");


            Cart::instance('default')->destroy();

            $mData = array(
                'name' => $request->fname,
                'email' => $request->email,
                'link' => "https://furniturevilletexas.com/invoice/".$otracker
                // 'link' => "127.0.0.1/invoice/".$otracker
            );

          /*  return redirect()->route('send')
                ->with('maildata' , $mData);*/

        } catch (CardErrorException $e) {

            return back()->withErrors('Error! ' . $e->getMessage());
        }

    }

    public function getPdf(Request $request, $id){
        $order = Order::find($id);
        // $products = $order->products();
        // $product_list = DB::table('order_products')->where('order_id', $order->id)->get();
        $product_list = DB::table('order_products')
            ->join('products','order_products.product_id','=', 'products.id')
            ->where('order_products.order_id', $id)
            ->get();
        $invoice = md5('fvt'.$id);
        $invoice = $invoice.'.pdf';

        $pdf = PDF::loadView('frontend.pages.invoicepdf', [
            'order' => $order,
            'id' => $id,
            'product_list' =>$product_list
        ]);

        return $pdf->stream('invoice_'.$invoice);

    }
}

app/Http/Controllers/Frontend/PasswordController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PasswordController extends Controller
{
    //


    public function index()
    {
        return view('auth.passwords.update');
    }

    public function update(Request $request){

        $uid = Auth()->user()->id;
        $user = User::find($uid);


        if(Hash::check($request->passwordold, $user['password']) ){
            if($request->passwordnew == $request->passwordconfirm){
                $user->password = bcrypt($request->passwordnew);
                $user->save();
                return redirect('frontend.my-account')->with('success_message','Password update successfully');

            }else{
                return redirect()->back()->with('error_massage','Confirm password doesn\'t match');
            }
        }
        else{
            return redirect()->back()->with('error_massage','Wrong password!');
        }

    }



}

resources/views/frontend/pages/cart.blade.php
@extends('frontend.layouts.master')
@section('title' , 'Cart')
@section('content')





    <!--=============================================
    =            Breadcrumb Area         =
    =============================================-->

    <div class="breadcrumb-area breadcrumb-bg pt-85 pb-85 mb-80">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-container">
                        <ul>
                            <li><a href="index.html">Home</a> <span class="separator">/</span></li>
                            <li class="active">Cart</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--=====  End of Breadcrumb Area  ======-->


    <!--=============================================
    =            Cart page content         =
    =============================================-->

    @if(Cart::instance('default')->count()>0)
        <div  class="container">
            <h4>{{Cart::instance('default')->count()}} item(s) in Shopping Cart</h4><br><br>
        </div>
        <div class="page-section mb-80">
            <div class="container">
                <div class="row">
                    <div class="col-12">

                        <!--=======  cart table  =======-->

                        <div class="cart-table table-responsive mb-40">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th class="pro-thumbnail">Image</th>
                                    <th class="pro-title">Product</th>
                                    <th class="pro-price">Price</th>
                                    <th class="pro-quantity">Quantity</th>
                                    <th class="pro-subtotal">Total</th>
                                    <th class="pro-remove">Remove</th>
                                    <th class="pro-remove">Update</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach(Cart::instance('default')->content() as $item)

                                    <tr>
                                        <form action="{{route('frontend.cart.update', $item->rowId)}}" method="POST">
                                            {!! csrf_field() !!}
                                            {{-- <span id="stock{{$item->model->id}}" > {{$item->model->stock }}</span>--}}
                                            <td class="pro-thumbnail"><a href="{{ route('frontend.shop.show',$item->model->slug) }}"><img src="{{ asset('uploads/'.$item->model->product_image)  }} " class="img-fluid" alt="Product"></a></td>
                                            <td class="pro-title"><a href="{{ route('frontend.shop.show',$item->model->slug) }}">{{$item->model->name}}</a></td>


                                            @if( $item->model->discount_price == 0 )


                                                <td class="pro-price"><span>৳{{$item->model->present_price}}</span></td>
                                            @else
                                                <td class="pro-price"><span>৳{{$item->model->discount_price}}</span></td>

                                            @endif


                                            <td class="pro-quantity"><div class="pro-qty">
                                                    <input type="text" name="quantity" id="quantity" max="{{$item->model->stock}}" value="{{$item->qty}}" >
                                                </div></td>


                                            {{--<td class="pro-subtotal"><span>{{$item->qty}}</span></td>--}}



                                            @if( $item->model->discount_price == 0 )


                                                <td class="pro-subtotal"><span>৳{{($item->qty)*$item->model->present_price}}</span></td>
                                            @else

                                                <td class="pro-subtotal"><span>৳{{($item->qty)*$item->model->discount_price}}</span></td>

                                            @endif


                                            <input name="id" type="hidden" value="{{$item->rowId}}">


                                            <td class="pro-remove"><a href="{{route('frontend.cart.destroy', $item->rowId)}}"><i class="fa fa-trash-o"></i></a></td>
                                            <td class="pro-remove">
                                                <button type="submit" class="">  <i class="fa fa-repeat"></i> </button>
                                            </td>
                                        </form>

                                    </tr>

                                @endforeach
                                </tbody>
                            </table>
                        </div>

                        <!--=======  End of cart table  =======-->


                        </form>

                        <div class="row">

                            <div class="col-lg-6 col-12">
                                <!--=======  Calculate Shipping  =======-->

                                <div class="calculate-shipping">
                                    <h4>Calculate Shipping</h4>
                                    <form action="#">
                                        <div class="row">
                                            <div class="col-md-6 col-12 mb-25">
                                                <select class="nice-select">
                                                    <option>Bangladesh</option>
                                                    <option>China</option>
                                                    <option>country</option>
                                                    <option>India</option>
                                                    <option>Japan</option>
                                                </select>
                                            </div>
                                            <div class="col-md-6 col-12 mb-25">
                                                <select class="nice-select">
                                                    <option>Dhaka</option>
                                                    <option>Barisal</option>
                                                    <option>Khulna</option>
                                                    <option>Comilla</option>
                                                    <option>Chittagong</option>
                                                </select>
                                            </div>
                                            <div class="col-md-6 col-12 mb-25">
                                                <input type="text" placeholder="Postcode / Zip">
                                            </div>
                                            <div class="col-md-6 col-12 mb-25">
                                                <input type="submit" value="Estimate">
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                <!--=======  End of Calculate Shipping  =======-->

                                <!--=======  Discount coupon  =======-->

                                @if(!session()->has('coupon'))
                                    <div class="discount-coupon">
                                        <h4>Discount Coupon Code</h4>
                                       <form action="{{ route('frontend.coupon.store') }}" method="POST">
                                            <div class="row">
                                                {{ csrf_field() }}
                                                <div class="col-md-6 col-12 mb-25">
                                                    <input type="text" name="coupon_code" id="coupon_code" placeholder="Coupon Code" required>
                                                    <input type="hidden" name="total" value="{{ Cart::instance('default')->total() }}">
                                                </div>
                                                <div class="col-md-6 col-12 mb-25">
                                                    <input type="submit" value="Apply Code">
                                                </div>
                                            </div>
                                      </form>


                                    </div>
                            @endif

                            <!--=======  End of Discount coupon  =======-->

                            </div>


                            <div class="col-lg-6 col-12 d-flex">
                                <!--=======  Cart summery  =======-->

                                <div class="cart-summary">
                                    <div class="cart-summary-wrap">
                                        <h4>Cart Summary</h4>
                                        <p>Sub Total <span>৳ {{Cart::instance('default')->total()}}</span></p>
                                        <p>Shipping Cost <span>৳ 00.00</span></p>
                                        @if(session()->has('coupon'))

                                            <p>Discount  [ {{ session()->get('coupon')['name'] }} ]

                                                <span>-৳{{ session()->get('coupon')['amount'] }}</span></p>
                                     <form action="{{ route('frontend.coupon.destroy') }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('delete') }}
                                                <button type="submit" style="background: black; color: white; border: none; margin-bottom: 2px;">Remove coupon</button>
                                            </form>

                                        @endif

                                        <h2>Grand Total <span>৳<?php
                                                $num1= (Cart::instance('default')->total());
                                                $num2= (session()->get('coupon')['amount']);
                                                $res =  (double)str_replace(',','',$num1)-
                                                    (double)str_replace(',','',$num2);
                                                echo $res;

                                                ?> </span></h2>
                                    </div>
                                    <div class="cart-summary-button">
                                        {{--<button>  <a href="{{route('checkout.index')}}"  class="checkout-btn">Checkout</a>  </button>--}}
                                        <a class="floating-cart-btn" href="{{route('frontend.checkout.index')}}">Checkout</a>
                                        {{--   <button class="update-btn pl-5">Update Cart</button>--}}
                                    </div>
                                </div>

                                <!--=======  End of Cart summery  =======-->

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>

        <!--=====  End of Cart page content  ======-->
    @else

        <div  class="container">
            <h4>No items in Cart!</h4><br><br>
        </div>

    @endif

    <!--=====  End of Cart page content  ======-->






@endsection()

resources/views/frontend/pages/confirmation.blade.php
@extends('frontend.layouts.master')

@section('content')
    <div class="container m-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6 mb-30">
                <h1>Thanks for your purchase</h1>
                <p>A mail has been sent to your email</p>
            </div>
        </div>
    </div>
@endsection