routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * to make new conttoller command
php artisan make:controller Frontend/IndexController --resource
*/

use Illuminate\Support\Facades\Route;

Auth::routes();


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
    ->middleware('role:admin')
    ->group(function (){

        //write your routes for backend
        Route::get('/', 'DashboardController@index')->name('dashboard');
//        products route
        Route::get('/products', 'ProductController@index')->name('product.list');
        Route::get('/product-add', 'ProductController@create')->name('product.add');
        Route::get('/product-edit/{id}', 'ProductController@edit')->name('product.edit');
//        for slug generation
        Route::get('/check_slug', 'ProductController@check_slug')->name('product.slug');
//        product create
        Route::post('/product-create', 'ProductController@store')->name('product.create');
        Route::post('/product-update', 'ProductController@update')->name('product.update');
        Route::post('/product-destroy', 'ProductController@destroy')->name('product.destroy');


//        category route
        Route::get('/category', 'CategoryController@index')->name('category.list');
        Route::get('/category-add', 'CategoryController@create')->name('category.add');
        Route::post('/category-create', 'CategoryController@store')->name('category.create');
        Route::get('/category-edit/{id}', 'CategoryController@edit')->name('category.edit');
        Route::post('/category-update', 'CategoryController@update')->name('category.update');
        Route::get('/category_slug', 'CategoryController@check_slug')->name('category.slug');

//        Order's route
        Route::get('/order','OrderController@index')->name('order.list');
        Route::get('/order/{id}','OrderController@show')->name('order.show');
        Route::get('/order-edit/{id}','OrderController@edit')->name('order.edit');
        Route::post('/order-update','OrderController@update')->name('order.update');
        Route::get('/pdf/{id}','OrderController@pdf')->name('order.pdf');


//        Slider route
        Route::get('/slider', 'SliderController@index')->name('slider.list');
        Route::get('/slider-add', 'SliderController@create')->name('slider.add');
        Route::post('/slider-create', 'SliderController@store')->name('slider.create');
        Route::get('/slider-edit/{id}', 'SliderController@edit')->name('slider.edit');
        Route::post('/slider-update', 'SliderController@update')->name('slider.update');
        Route::post('/slider-destroy', 'SliderController@destroy')->name('slider.destroy');

//        coupon route
        Route::get('coupon','CouponController@index')->name('coupon.list');
        Route::get('coupon/new','CouponController@new')->name('coupon.add');
        Route::post('coupon/create','CouponController@create')->name('coupon.create');
        Route::get('coupon/edit/{id}','CouponController@edit')->name('coupon.edit');
        Route::post('coupon/update','CouponController@update')->name('coupon.update');
        Route::post('coupon/destroy','CouponController@destroy')->name('coupon.destroy');

//        reviews controller for admin
        Route::get('reviews', 'AdminReviewController@index')->name('reviews.list');
        Route::get('reviews/show/{id}', 'AdminReviewController@show')->name('reviews.show');
        Route::post('/review-destroy', 'AdminReviewController@destroy')->name('reviews.destroy');


        //        Fetured Categories route
        Route::get('/featuredcategories', 'FeaturedCategoryController@index')->name('featuredcategories.list');
        Route::get('/featuredcategories-add', 'FeaturedCategoryController@create')->name('featuredcategories.add');
        Route::post('/featuredcategories-create', 'FeaturedCategoryController@store')->name('featuredcategories.create');
        Route::get('/featuredcategories-edit/{id}', 'FeaturedCategoryController@edit')->name('featuredcategories.edit');
        Route::post('/featuredcategories-update', 'FeaturedCategoryController@update')->name('featuredcategories.update');
        Route::post('/featuredcategories-destroy', 'FeaturedCategoryController@destroy')->name('featuredcategories.destroy');

//        sales report
        Route::get('/sales-report', 'ReportController@index')->name('report.index');

        Route::get('/users', 'FeedbackController@userList')->name('user.list');
        Route::get('/users/{id}', 'FeedbackController@userShow')->name('user.show');

        Route::get('/feedback', 'FeedbackController@index')->name('feedback.list');
        Route::get('/feedback/{id}', 'FeedbackController@show')->name('feedback.show');
        Route::get('/newsletter', 'NewsletterController@index')->name('newsletter.index');
    });


Route::name('frontend.')
    ->namespace('Frontend')
    ->group(function (){

        //write your routes for frontend
       Route::get('/','IndexController@index' )->name('index');

      // shop route
        Route::get('/shop/{product}', 'ShopController@show')->name('shop.show');
        Route::get('/shop', 'ShopController@index')->name('shop.index');

        // cart route

        Route::get('/cart', 'CartController@index')->name('cart.index');
        Route::post('/cart', 'CartController@store')->name('cart.store');
        Route::get('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
        Route::post('/cart/{product}', 'CartController@update')->name('cart.update');


        ///wish list

        Route::post('/wishlist', 'WishlistController@store')->name('wishlist.store');
        Route::get('/wishlist', 'WishlistController@index')->name('wishlist.index');
        Route::get('/wishlist/{product}', 'WishlistController@destroy')->name('wishlist.destroy');

        //checkout
        Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');

        // coupon route
        Route::post('/coupon', 'CartController@storeCoupon')->name('coupon.store');
        Route::delete('/coupon', 'CartController@destroyCoupon')->name('coupon.destroy');

        //        review
        Route::post('/review-add','ReviewController@store')->name('review.store');
//        newsletter
        Route::get('/newsletter-add', 'IndexController@newsletter')->name('newsletter.add');
        Route::post('/feedback-add', 'IndexController@feedback')->name('feedback.add');




        //my accout

        Route::get('/my-account', 'OrderIndexController@index')->middleware('auth')->name('my-account');
        Route::post('/my-account', 'OrderIndexController@store')->middleware('auth')->name('my-account.store');

        // password update
        Route::get('/password-update', 'PasswordController@index')->name('password-update');

        Route::post('update/password', 'PasswordController@update')->name('update-pass');

        Route::get('/search', 'ShopController@search')->name('search');

       Route::get('/about', function () {
                 return view('frontend.pages.about');
             });

                Route::get('/contact', function () {
                return view('frontend.pages.contact');
            });
                Route::get('/compare', function () {
                 return view('frontend.pages.compare');
             });
             Route::get('/blog', function () {
                 return view('frontend.pages.blog');
             });
             Route::get('/post', function () {
                 return view('frontend.pages.post');
             });

             Route::get('/faq', function () {
                 return view('frontend.pages.faq');
             });



    });

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{

    protected $fillable = [
        'user_id', 'billing_email','billing_first_name','billing_last_name','billing_phone_no','billing_address','billing_town',
        'billing_city','billing_zip_code','billing_id','billing_discount','billing_discount_code','billing_subtotal','billing_shipping_fee'
        ,'billing_total','billing_payment_gateway',
        'shipped','status'
    ];

    public function user(){
        return $this->belongsTo('app\User');
    }
    public function products(){
        return $this->belongsToMany('App\Product')->withPivot('quantity');
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Order;
use App\OrderProduct;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use MercurySeries\Flashy\Flashy;

class OrderController extends Controller
{

    public function index() {

        $orders = Order::orderBy('id','DESC')->get();

        return view('backend.pages.order.list')->with([
            'orders' => $orders
        ]);
    }


    public function create()
    {
        //
    }


    public function pdf($id) {
        $order = Order::find($id);
        $products = OrderProduct::select('order_products.quantity as amount', 'products.name as productName',
            'products.slug as slug','order_products.price as rate')
            ->join('products','order_products.product_id','=','products.id')
            ->where('order_products.order_id', $id)
            ->get();


        $pdf = PDF::loadView('backend.pages.order.invoice', [
            'order' => $order,
            'products' => $products
        ]);
        return $pdf->stream('invoice.pdf');
    }


    public function show($id) {

        $order = Order::find($id);

        $products = OrderProduct::select('order_products.quantity as amount', 'products.name as productName',
            'products.slug as slug','order_products.price as rate')
            ->join('products','order_products.product_id','=','products.id')
            ->where('order_products.order_id', $id)
            ->get();

        return view('backend.pages.order.show')->with([
            'order' => $order,
            'products' =>$products
        ]);
    }


    public function edit($id) {

        $order = Order::find($id);

        return view('backend.pages.order.edit')->with([
            'order' => $order
        ]);
    }

    public function update(Request $request)
    {
        $order = Order::find($request->id);

        $order->status = $request->status;
        $order->billing_address = $request->address;
        $order->billing_town = $request->town;
        $order->billing_phone_no = $request->number;

        $order->save();

        Flashy::success('Order update successful', '');
        return redirect()->route('backend.order.list');

    }


    public function destroy($id)
    {
        //
    }
}

resources/views/backend/pages/order/edit.blade.php
@extends('backend.layouts.app')

@section('title', 'Update Order')

@section('content')
    <section class="content-header">
        <h1>
            Order's Report
            <small>You can download as csv</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('backend.dashboard') }}"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="{{ route('backend.order.list') }}"><i class="fa fa-bank"></i> Order's Report</a></li>
            <li class="active">Order update</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="invoice">
        <!-- title row -->
        <div class="row">
            <div class="col-xs-12">
                <h2 class="page-header">
                    <i class="fa fa-globe"></i>  Jahangir Enterprice
                    <small class="pull-right">Date: {{ date('F j, Y, g:i:s a', strtotime( $order->created_at)) }}</small>
                </h2>
            </div>
            <!-- /.col -->
        </div>

        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
            To
            <address>
                <strong>{{ $order->billing_first_name }} {{ $order->billing_last_name }}</strong><br>
                input{{ $order->billing_address }}<br>
                {{ $order->billing_town }}, {{ $order->billing_city}} &nbsp;
                {{ $order->billing_zip_code }} <br>
                Phone: {{ $order->billing_phone_no }}<br>
                Email: {{ $order->billing_email }}
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
            <b>Invoice #{{ $order->id + 1000 }}</b><br>
            <br>
            <b>Order ID:</b> 4F3S8J<br>
            <br>
        </div>
        <!-- /.col -->


        <form class="form-horizontal" action="{{ route('backend.order.update') }}" method="post">
            <div class="col-sm-4 invoice-col">

                <b>Ordered: </b> {{ $order->created_at }} <br>
                <b>Last Update: </b> {{ $order->updated_at }} <br> <br>
                <div class="form-group">
                    <label for="status" class="col-sm-6 control-label">Order Status</label>
                    <div class="col-sm-6">
                        <select name="status" id="status" class="form-group">
                            <option value="{{ $order->status }}" disabled>{{ $order->status }}</option>
                            <option value="Pending" >Pending</option>
                            <option value="Declined" style=" color: #b83400">Declined</option>
                            <option value="Approved" style=" color: #00A9F0">Approved</option>
                            <option value="Delivered" style=" color: #00cc66">Delivered</option>
                            <option value="Refund Request">Refund Request</option>
                            <option value="Refunded">Refunded</option>
                        </select>
                    </div>
                </div>

            </div>
            <div class="clearfix"></div>
            @csrf
            <input type="hidden" class="form-control"  name="id" value="{{ $order->id }}" >

            <div class="box-body">



                <div class="form-group">
                    <label for="address" class="col-sm-2 control-label">Billing Address</label>

                    <div class="col-sm-4">
                        <textarea name="address" id="address" cols="50" rows="3">{{ $order->billing_address }}</textarea>
                    </div>
                    <label for="town" class="col-sm-2 control-label">Town </label>

                    <div class="col-sm-4">
                        <input type="text" class="form-control"  id="town" name="town" value="{{ $order->billing_town}}" >
                    </div>

                </div>
                <div class="form-group">
                    <label for="number" class="col-sm-2 control-label">Contact No.</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="number"  name="number" value="{{ $order->billing_phone_no}}" >
                    </div>

                </div>


                </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <a href="{{  route('backend.order.list') }}" class="btn btn-info">Cancel</a>
                <button type="submit" class="btn btn-success pull-right">Update Order</button>
            </div>
            <!-- /.box-footer -->
        </form>



    </section>


@endsection

resources/views/backend/pages/order/list.blade.php
@extends('backend.layouts.app')

@section('title', 'Order statement')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Order's Report
            <small>You can download as csv</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('backend.dashboard') }}"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li class="active">Order</li>
        </ol>
    </section>

    <div class="box">
        <div class="box-header">


            <div class="col-md-6 ">
                <a href="#" class="btn btn-success">Download csv</a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="list" class="table table-bordered table-striped table-responsive table-hover" >
                <thead>
                <tr>
                    <th>#</th>
                    <th>Email</th>
                    <th>City</th>
                    <th>Total Bill</th>
                    <th>Status</th>
                    <th>Order time</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($orders as $order)
                    <tr>
                        <td>{{ $order->id }}</td>
                        <td>{{ $order->billing_email }}</td>
                        <td>{{ $order->billing_town }}, {{ $order->billing_city }}</td>
                        <td>{{ $order->billing_total }}</td>
                        <td>
                            @if($order->status == 'Pending')
                                <span class=" badge alert-info">&nbsp; {{ $order->status }} &nbsp;</span>
                            @elseif($order->status == 'Declined')
                                <span class=" badge alert-error">&nbsp; {{ $order->status }} &nbsp;</span>
                            @elseif($order->status == 'Payment_failed')
                                <span class="badge alert-dark">&nbsp; {{ $order->status }} &nbsp;</span>
                            @elseif($order->status == 'Approved')
                                <span class="badge alert-success">&nbsp; {{ $order->status }} &nbsp;</span>
                            @elseif($order->status == 'Refund Request')
                                <span class="badge alert-warning"> &nbsp;{{ $order->status }} &nbsp;</span>
                            @elseif($order->status == 'Refunded')
                                <span class="badge alert-secondary">&nbsp; {{ $order->status }} &nbsp;</span>
                            @elseif($order->status == 'Delivered')
                                <span class="badge alert-success">&nbsp; {{ $order->status }} &nbsp;</span>
                            @endif
                        </td>
                        <td>{{ $order->created_at }}</td>
                        <td>
                            <a href="{{ route('backend.order.show',['id'=> $order->id]) }}"><i class="fa fa-envelope-open fa-lg" style="color:dodgerblue" aria-hidden="true"></i> </a>&nbsp;&nbsp;
                            <a href="{{ route('backend.order.edit',['id'=> $order->id]) }}"><i class="fa fa-pencil-square fa-lg" style="color:forestgreen" aria-hidden="true"></i> </a>&nbsp;&nbsp;
                            {{--<a href=""><i class="fa fa-trash fa-lg deletebtn" data-id="{{ $order->id }}"--}}
                                          {{--data-name="{{ $order->mail }}" data-token="{{ @csrf_token() }}" style="color:red"></i> </a>--}}
                        </td>

                    </tr>
                @endforeach

                </tbody>
                <tfoot>
                <tr>
                    <th>#</th>
                    <th>Email</th>
                    <th>City</th>
                    <th>Total Bill</th>
                    <th>Status</th>
                    <th>Order time</th>
                    <th>Action</th>
                </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
    </div>



@endsection

@push('scripts')


    {{-- DataTable js --}}
    <link rel="stylesheet" href="{{asset('backend/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <script src="{{asset('backend/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{asset('backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(function () {
            $('#list').DataTable();
        });

    </script>
@endpush

resources/views/backend/pages/order/pdf.blade.php
<h1>Jahangir Enterprice</h1>
<pre>
    Haji Khalek Gamsa Super Market,
    Shekherchar Bazar, Mosjid road,
    Gamsa potti,Madhabdi.

Mobile: +88 017 11 227 959
Email: jh.jahangir227@gmail.com </pre>
<div class="clearfix"></div>
<div class="row">
    <div align="right">
        Order Time:  {{ date('F j, Y, g:i:s a', strtotime( $order->created_at)) }}
    </div>
    <div class="col-md-6">
        <h1> Order No. #{{ $order->id + 1000 }} </h1>
        <p>Invoice # FVT{{ substr(md5('muaj'.$order->id.'saif'), 0, 15) }}</p>
        <p>Tracker : {{ substr(md5('muaj'.$order->id.'saif'), 16, 31) }} </p>

    </div>

</div>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Product Name</th>
        <th>Product slug</th>
        <th>Qty</th>
        <th>Rate</th>
        <th>Subtotal</th>
    </tr>
    </thead>
    <tbody>
    @php
        $no=0;
        $total = 0;
    @endphp
    @foreach($products as $product)
        @php
            $total = $total + $product->rate * $product->amount;
        @endphp
        <tr>
            <td>{{ $product->productName }}</td>
            <td>{{ $product->slug }}</td>
            <td>{{ $product->amount }}</td>
            <td>{{ $product->rate }} ৳</td>
            <td>{{ $product->rate * $product->amount }} ৳</td>

        </tr>
    @endforeach


    <tr style="background-color: #96C2CA;  color:black; font-size: 1.1em;">
        <td></td>
        <td></td>
        <td></td>
        <td>Sub-Total</td>
        <td> $ {{ $total }}</td>
    </tr>
    </tbody>
</table>

<div class="clearfix"></div>
<div class="row">
    <div class="col-md-6 col-sm-12">
        Order Details:
        <pre>

    Name: {{ $order->billing_first_name}} {{ $order->billing_last_name}}
    Email: {{ $order->billing_email}}
    Phone: {{ $order->billing_phone_no}}

Shipping Details:    
    Shipping Address: {{ $order->billing_address}}
    Town : {{ $order->billing_town}}
    City : {{ $order->billing_city}}
    Zip code : {{ $order->billing_zip_code}}
</pre>
    </div>
    <div class="col-md-6 col-sm-12">
        Billing Details:
        <pre>
    Payment Method: {{ $order->billing_payment_gateway}}
    Order Sub total: {{ $order->billing_subtotal}}
    Discount: {{ $order->billing_discount ? $order->billing_discount : '0'}}
    Shipping Cost: {{ $order->billing_shipping_cost ? $order->billing_shipping_cost : '0'}}
    Total amount: {{ $order->billing_total}}
        </pre>
    </div>
</div>

resources/views/backend/pages/order/show.blade.php
@extends('backend.layouts.app')

@section('title', 'Order detail')

@section('content')
    <section class="content-header">
        <h1>
            Order's Detail
            <small> </small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('backend.dashboard') }}"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="{{ route('backend.order.list') }}"><i class="fa fa-dashboard"></i> Order</a></li>
            <li class="active">Order Detail</li>
        </ol>
    </section>

    <!-- Content Wrapper. Contains page content -->
    <div class="content ">
        <!-- this row will not appear when printing -->
        <div class="row no-print">
            <div class="col-xs-12">
                <a href="{{ route('backend.order.pdf',['id' => $order->id]) }}" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>

                <a href="{{ route('backend.order.pdf',['id' => $order->id]) }}" class="btn btn-primary pull-right" style="margin-right: 5px;">
                    <i class="fa fa-download"></i> Generate PDF
                </a>

            </div>
        </div>

        {{--<div class="pad margin no-print">--}}
            {{--<div class="callout callout-info" style="margin-bottom: 0!important;">--}}
                {{--<h4><i class="fa fa-info"></i> Note:</h4>--}}
                {{--This page has been enhanced for printing. Click the print button at the bottom of the invoice to test.--}}
            {{--</div>--}}
        {{--</div>--}}

        <!-- Main content -->
        <section class="invoice">
            <!-- title row -->
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="page-header">
                        <i class="fa fa-globe"></i> {{ config('app.name', 'JahangirEnterprice') }}
                        <small class="pull-right">Date: {{ date('F j, Y, g:i:s a', strtotime( $order->created_at)) }}</small>
                    </h2>
                </div>
                <!-- /.col -->
            </div>
            <!-- info row -->
            <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                    From
                    <address>
                        <strong>Jahangir Enterprice</strong><br>
                        Haji Khalek Gamsa Super Market,<br>
                        Shekherchar Bazar, Mosjid road, <br>
                        Gamsa potti,Madhabdi. <br>
                        Phone: +88 017 11 227 959<br>
                        Email: jh.jahangir227@gmail.com
                    </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                    To
                    <address>
                        <strong>{{ $order->billing_first_name }} {{ $order->billing_last_name }}</strong><br>
                        {{ $order->billing_address }}<br>
                        {{ $order->billing_town }}, {{ $order->billing_city}} &nbsp;
                        {{ $order->billing_zip_code }} <br>
                        Phone: {{ $order->billing_phone_no }}<br>
                        Email: {{ $order->billing_email }}
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                    <b>Invoice #{{ $order->id + 1000 }}</b><br>
                    <br>
                    <b>Order ID:</b> 4F3S8J<br>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->

            <!-- Table row -->
            <div class="row">
                <div class="col-xs-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Product Name</th>
                            <th>Product slug</th>
                            <th>Qty</th>
                            <th>Rate</th>
                            <th>Subtotal</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($products as $product)
                        <tr>
                            <td>{{ $product->productName }}</td>
                            <td>{{ $product->slug }}</td>
                            <td>{{ $product->amount }}</td>
                            <td>{{ $product->rate }}</td>
                            <td>{{ $product->rate * $product->amount }} ৳</td>

                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->

            <div class="row">
                <!-- accepted payments column -->
                <div class="col-xs-6">
                    <p class="lead">Payment Methods:</p>
                    <p>Payer name: {{ $order->billing_first_name }} {{ $order->billing_last_name }}</p>


                    <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                         Payment Method: {{ $order->billing_payment_gateway }} <br>
                         Paid Amount: {{ $order->billing_total }} <br>
                         Transection ID: {{ $order->billing_id }} <br>
                    </p>
                </div>
                <!-- /.col -->
                <div class="col-xs-6">

                    <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <th style="width:50%">Subtotal:</th>
                                <td>{{ $order->billing_subtotal }} ৳</td>
                            </tr>
                            <tr>
                                <th>Shipping:</th>
                                <td>{{ $order->shipping_fee }} ৳</td>
                            </tr>
                            <tr>
                                <th>Discount:</th>
                                <td>{{ $order->discount }} ৳</td>
                            </tr>
                            <tr>
                                <th>Total:</th>
                                <td>{{ $order->billing_total }} ৳</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.row -->


        </section>
        <!-- /.content -->
        <div class="clearfix"></div>
    </div>
    <!-- /.content-wrapper -->


@endsection