routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * to make new conttoller command
php artisan make:controller Frontend/IndexController --resource
*/

use Illuminate\Support\Facades\Route;

Auth::routes();


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
    ->middleware('role:admin')
    ->group(function (){

        //write your routes for backend
        Route::get('/', 'DashboardController@index')->name('dashboard');
//        products route
        Route::get('/products', 'ProductController@index')->name('product.list');
        Route::get('/product-add', 'ProductController@create')->name('product.add');
        Route::get('/product-edit/{id}', 'ProductController@edit')->name('product.edit');
//        for slug generation
        Route::get('/check_slug', 'ProductController@check_slug')->name('product.slug');
//        product create
        Route::post('/product-create', 'ProductController@store')->name('product.create');
        Route::post('/product-update', 'ProductController@update')->name('product.update');
        Route::post('/product-destroy', 'ProductController@destroy')->name('product.destroy');


//        category route
        Route::get('/category', 'CategoryController@index')->name('category.list');
        Route::get('/category-add', 'CategoryController@create')->name('category.add');
        Route::post('/category-create', 'CategoryController@store')->name('category.create');
        Route::get('/category-edit/{id}', 'CategoryController@edit')->name('category.edit');
        Route::post('/category-update', 'CategoryController@update')->name('category.update');
        Route::get('/category_slug', 'CategoryController@check_slug')->name('category.slug');

//        Order's route
        Route::get('/order','OrderController@index')->name('order.list');
        Route::get('/order/{id}','OrderController@show')->name('order.show');
        Route::get('/order-edit/{id}','OrderController@edit')->name('order.edit');
        Route::post('/order-update','OrderController@update')->name('order.update');
        Route::get('/pdf/{id}','OrderController@pdf')->name('order.pdf');


//        Slider route
        Route::get('/slider', 'SliderController@index')->name('slider.list');
        Route::get('/slider-add', 'SliderController@create')->name('slider.add');
        Route::post('/slider-create', 'SliderController@store')->name('slider.create');
        Route::get('/slider-edit/{id}', 'SliderController@edit')->name('slider.edit');
        Route::post('/slider-update', 'SliderController@update')->name('slider.update');
        Route::post('/slider-destroy', 'SliderController@destroy')->name('slider.destroy');

//        coupon route
        Route::get('coupon','CouponController@index')->name('coupon.list');
        Route::get('coupon/new','CouponController@new')->name('coupon.add');
        Route::post('coupon/create','CouponController@create')->name('coupon.create');
        Route::get('coupon/edit/{id}','CouponController@edit')->name('coupon.edit');
        Route::post('coupon/update','CouponController@update')->name('coupon.update');
        Route::post('coupon/destroy','CouponController@destroy')->name('coupon.destroy');

//        reviews controller for admin
        Route::get('reviews', 'AdminReviewController@index')->name('reviews.list');
        Route::get('reviews/show/{id}', 'AdminReviewController@show')->name('reviews.show');
        Route::post('/review-destroy', 'AdminReviewController@destroy')->name('reviews.destroy');


        //        Fetured Categories route
        Route::get('/featuredcategories', 'FeaturedCategoryController@index')->name('featuredcategories.list');
        Route::get('/featuredcategories-add', 'FeaturedCategoryController@create')->name('featuredcategories.add');
        Route::post('/featuredcategories-create', 'FeaturedCategoryController@store')->name('featuredcategories.create');
        Route::get('/featuredcategories-edit/{id}', 'FeaturedCategoryController@edit')->name('featuredcategories.edit');
        Route::post('/featuredcategories-update', 'FeaturedCategoryController@update')->name('featuredcategories.update');
        Route::post('/featuredcategories-destroy', 'FeaturedCategoryController@destroy')->name('featuredcategories.destroy');

//        sales report
        Route::get('/sales-report', 'ReportController@index')->name('report.index');

        Route::get('/users', 'FeedbackController@userList')->name('user.list');
        Route::get('/users/{id}', 'FeedbackController@userShow')->name('user.show');

        Route::get('/feedback', 'FeedbackController@index')->name('feedback.list');
        Route::get('/feedback/{id}', 'FeedbackController@show')->name('feedback.show');
        Route::get('/newsletter', 'NewsletterController@index')->name('newsletter.index');
    });


Route::name('frontend.')
    ->namespace('Frontend')
    ->group(function (){

        //write your routes for frontend
       Route::get('/','IndexController@index' )->name('index');

      // shop route
        Route::get('/shop/{product}', 'ShopController@show')->name('shop.show');
        Route::get('/shop', 'ShopController@index')->name('shop.index');

        // cart route

        Route::get('/cart', 'CartController@index')->name('cart.index');
        Route::post('/cart', 'CartController@store')->name('cart.store');
        Route::get('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
        Route::post('/cart/{product}', 'CartController@update')->name('cart.update');


        ///wish list

        Route::post('/wishlist', 'WishlistController@store')->name('wishlist.store');
        Route::get('/wishlist', 'WishlistController@index')->name('wishlist.index');
        Route::get('/wishlist/{product}', 'WishlistController@destroy')->name('wishlist.destroy');

        //checkout
        Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');

        // coupon route
        Route::post('/coupon', 'CartController@storeCoupon')->name('coupon.store');
        Route::delete('/coupon', 'CartController@destroyCoupon')->name('coupon.destroy');

        //        review
        Route::post('/review-add','ReviewController@store')->name('review.store');
//        newsletter
        Route::get('/newsletter-add', 'IndexController@newsletter')->name('newsletter.add');
        Route::post('/feedback-add', 'IndexController@feedback')->name('feedback.add');




        //my accout

        Route::get('/my-account', 'OrderIndexController@index')->middleware('auth')->name('my-account');
        Route::post('/my-account', 'OrderIndexController@store')->middleware('auth')->name('my-account.store');

        // password update
        Route::get('/password-update', 'PasswordController@index')->name('password-update');

        Route::post('update/password', 'PasswordController@update')->name('update-pass');

        Route::get('/search', 'ShopController@search')->name('search');

       Route::get('/about', function () {
                 return view('frontend.pages.about');
             });

                Route::get('/contact', function () {
                return view('frontend.pages.contact');
            });
                Route::get('/compare', function () {
                 return view('frontend.pages.compare');
             });
             Route::get('/blog', function () {
                 return view('frontend.pages.blog');
             });
             Route::get('/post', function () {
                 return view('frontend.pages.post');
             });

             Route::get('/faq', function () {
                 return view('frontend.pages.faq');
             });



    });

app/Coupon.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    public static function findByCode($code){
        return self::where('code', $code)->first();
    }

    public function discount($total)
    {
        if ($this->type == 'fixed') {
            return $this->value;
        }
        else {

            $off = round(( $this->percent_off / 100) * $total);

            return $off;
        }
    }
}

app/Http/Controllers/Backend/CouponController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Coupon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use MercurySeries\Flashy\Flashy;

class CouponController extends Controller
{

    public function index()
    {
        $coupon = Coupon::all();
        return view('backend.pages.coupon.list')->with('coupons',$coupon);
    }

    public function new()
    {
        $coupon = Coupon::all();
        return view('backend.pages.coupon.add')->with('coupons',$coupon);


    }
    public function create(Request $request) {

        $coupon = new Coupon();

        $coupon->code = $request->couponCode;
        $coupon->type = $request->couponType;
        $coupon->value = $request->couponValue;
        $coupon->percent_off = $request->couponPercentage;
        $coupon->expire = $request->couponExpireDate;

        $coupon->save();

        Flashy::success(' New Coupon '. $request->couponCode.' created.');
        return redirect()->back();

    }


    public function store(Request $request)
    {
        $code = Coupon::where('code', $request->coupon_code)->first();

        if(!$code){
            return redirect()->route('cart.index')->with('success_message', 'Invalid coupon !');
        }
        session()->put('coupon', [
            'name' => $code->code,
            'amount' =>$code->discount(Cart::subtotal())
        ]);
        return redirect()->route('cart.index')->with('success_message', 'coupon Applied ');
    }


    public function show($id) {
        //
    }


    public function edit($id)
    {
        $coupon = Coupon::find($id);


        return view('backend.pages.coupon.edit')->with([
            'coupon' => $coupon
        ]);
    }


    public function update(Request $request) {

        $coupon = Coupon::find($request->id);

        $coupon->code = $request->couponCode;
        $coupon->type = $request->couponType;
        $coupon->value = $request->couponValue;
        $coupon->percent_off = $request->couponPercentage;
        $coupon->expire = $request->couponExpireDate;

        $coupon->save();

        Flashy::success('  Coupon '. $request->couponCode.' updated.');

        return redirect()->route('backend.coupon.list');
    }


    public function destroy()
    {
        session()->forget('coupon');
        return back()->with('success_message', 'coupon has been removed.');
    }
}

resources/views/backend/pages/coupon/add.blade.php
@extends('backend.layouts.app')

@section('title', 'New Coupon')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            New Coupon
            <small>Create a new Coupon</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="#"><i class="fa fa-barcode"></i> Coupon</a></li>
            <li class="active">New Coupon</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content container-fluid">

        <div class="coupon">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <!-- form start -->
                <form class="form-horizontal" action="{{ route('backend.coupon.create') }}" method="post"
                      enctype="multipart/form-data">
                    @csrf
                    <div class="box-body">
                            <div class="form-group">

                            <label for="couponCode" class="col-sm-2 control-label">Coupon Code *</label>

                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="couponCode" name="couponCode" placeholder="New Coupon code.." required>
                            </div>
                            <label for="couponType" class="col-sm-1 control-label">Type</label>

                            <div class="col-sm-3">
                                <select class="form-control " id="couponType" name="couponType">
                                        <option value="fixed">Fixed</option>
                                        <option value="percent_off">Percent Off</option>
                                </select>
                            </div>
                            </div>
                            <div class="form-group">
                                <label for="couponValue" class="col-sm-2 control-label">Discount Amount</label>
                                <div class="col-sm-5">
                                    <input type="text" class="form-control" id="couponValue" name="couponValue" placeholder="For Fixed amout"  >
                                </div>
                                <div class="col-sm-5">
                                    <input type="text" class="form-control" id="couponValue" name="couponPercentage" placeholder="For Percentage discount"  >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="couponExpire" class="col-sm-2 control-label">Expire Date</label>
                                <div class="col-sm-5">
                                    <input type="date" class="form-control" id="couponExpire" name="couponExpireDate" placeholder="Expire"  >
                                </div>
                            </div>


                    </div>

                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-info pull-right">Create Coupon</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
    </section>

    <section class="container">
        <cite><h5>* Please use unique coupon code name</h5></cite>
        <cite><h5>* Expire date feature is not available</h5></cite>
        <br>
        <h5>Coupon's name already active below</h5>
        <table>
            <tr>
            @foreach($coupons as $coupon)
                <li style="list-style-type: none; text-decoration: underline; display: inline; padding-right: 3px" >
                    {{$coupon['code'] }}
                </li>
                @endforeach
            </tr>
        </table>
    </section>

@endsection

resources/views/backend/pages/coupon/edit.blade.php
@extends('backend.layouts.app')

@section('title', 'Coupon edit')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Edit Coupon
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="#"><i class="fa fa-barcode"></i> Coupon</a></li>
            <li class="active">Edit Coupon</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content container-fluid">

        <div class="coupon">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <!-- form start -->
                <form class="form-horizontal" action="{{ route('backend.coupon.update') }}" method="post"
                      enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" class="form-control" id="couponCode" name="id"  value="{{ $coupon->id }}">

                    <div class="box-body">
                        <div class="form-group">

                            <label for="couponCode" class="col-sm-2 control-label">Coupon Code *</label>

                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="couponCode" name="couponCode" value="{{ $coupon->code }}" required>
                            </div>
                            <label for="couponType" class="col-sm-1 control-label">Type</label>

                            <div class="col-sm-3">
                                <select class="form-control " id="couponType" name="couponType">
                                    <option value="{{ $coupon->type }}"">{{ $coupon->type }}"</option>
                                    <option value="fixed">Fixed</option>
                                    <option value="percent_off">Percent Off</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="couponValue" class="col-sm-2 control-label">Discount Amount</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="couponValue" name="couponValue" value="{{ $coupon->value }}"  >
                            </div>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="couponValue" name="couponPercentage"  value="{{ $coupon->percent_off }}" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="couponExpire" class="col-sm-2 control-label">Expire Date</label>
                            <div class="col-sm-5">
                                <input type="date" class="form-control" id="couponExpire" name="couponExpireDate" value="{{ $coupon->expire }}"  >
                            </div>
                        </div>


                    </div>

                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-info pull-right">Update Coupon</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
    </section>

    <section class="container">
        <cite><h5>* Please use unique coupon code name</h5></cite>
        <cite><h5>* Expire date feature is not available</h5></cite>
        <br>

    </section>


@endsection

resources/views/backend/pages/coupon/list.blade.php
@extends('backend.layouts.app')

@section('title', 'coupon')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Coupon
            <small><a href="{{ route('backend.coupon.add') }}" class="btn btn-success">New Coupon</a></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li class="active">Coupon</li>
        </ol>
    </section>

    <div class="box">
        <!-- /.box-header -->

        <div class="box-body">
            <table id="coupon-list" class="table table-bordered table-striped table-responsive table-hover" >
                <thead>
                <tr>
                    <th>#</th>
                    <th>Coupon code</th>
                    <th>Type</th>
                    <th>Fixed value</th>
                    <th>Percentage value</th>
                    <th>Created at</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($coupons as $coupon)
                    <tr>
                        <td>{{ $coupon->id }}</td>
                        <td>{{ $coupon->code }}</td>
                        <td>{{ $coupon->type }}</td>
                        <td>{{ $coupon->value }}</td>
                        <td>{{ $coupon->percent_off }}</td>
                        <td>{{ $coupon->created_at }}</td>
                        <td>
                            <a href="{{ route('backend.coupon.edit',['id'=> $coupon->id]) }}"><i class="fa fa-pencil-square fa-lg" style="color:dodgerblue" aria-hidden="true"></i> </a> &nbsp;
                            <a href=""><i class="fa fa-trash fa-lg deletebtn" data-id="{{ $coupon->id }}"
                                          data-name="{{ $coupon->code }}" data-token="{{ @csrf_token() }}" style="color:red"></i> </a>
                        </td>

                    </tr>
                @endforeach

                </tbody>
                <tfoot>
                <tr>
                    <th>#</th>
                    <th>Coupon code</th>
                    <th>Type</th>
                    <th>Fixed value</th>
                    <th>Percentage value</th>
                    <th>Created at</th>
                    <th>Action</th>
                </tr>
                </tfoot>
            </table>

        </div>
    </div>

@endsection

@push('scripts')


    {{-- DataTable js --}}
    <link rel="stylesheet" href="{{asset('backend/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <script src="{{asset('backend/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{asset('backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(function () {
            $('#coupon-list').DataTable();
        });

        $(document).on('click', '.deletebtn', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var token = $(this).data('token');
            var name = $(this).data('name');
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'Danger',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: "POST",
                        url: "{{ route('backend.product.destroy') }}",
                        data: {id:id, _token:token},
                        success: function (data) {
                            if(data.success == true){ // if true (1)
                                setTimeout(function(){  // wait for 5 secs(2)
                                    location.reload();  // then reload the page.(3)
                                }, 500);
                            }
                        }
                    });

                    swal(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            });

        });


    </script>
@endpush